version: "3.8"

services:

  configserver:
    image: darthkali/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - czezchznet

  movieservice:
    image: darthkali/movies:latest
    ports:
      - "8080:8080"
    networks:
      - czezchznet
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  czezchznet: