version: "3.8"
services:
  common_microservice:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092