# run using
# docker compose -f compose-local.yml build
version: "2.4"

services:
  ########################
  ########## GATEWAY
  gateway:
    extends:
      file: common_infrastructure.yml
      service: gateway

  ########################
  ########## MESSAGING
  zookeeper:
    extends:
      file: common_infrastructure.yml
      service: zookeeper

  kafka:
    extends:
      file: common_infrastructure.yml
      service: kafka

  ########################
  ########## DATABASES
  movieservice_db:
    extends:
      file: common_infrastructure.yml
      service: db

  cinemaservice_db:
    extends:
      file: common_infrastructure.yml
      service: db

  showservice_db:
    extends:
      file: common_infrastructure.yml
      service: db

  bookingservice_db:
    extends:
      file: common_infrastructure.yml
      service: db

  ########################
  ########## MICROSERVICES
  movieservice:
    extends:
      file: microservices.yml
      service: movieservice
    build:
      context: ../movieservice
      dockerfile: ../movieservice/Dockerfile
    image: "fh-erfurt/microkino:movieservice"
    # Services will not share depends_on when using 'extends'
    depends_on:
      - kafka
      - movieservice_db

  cinemaservice:
    extends:
      file: microservices.yml
      service: cinemaservice
    build:
      context: ../cinemaservice
      dockerfile: ../cinemaservice/Dockerfile
    image: "fh-erfurt/microkino:cinemaservice"
    depends_on:
      - kafka
      - cinemaservice_db


  showservice:
    extends:
      file: microservices.yml
      service: showservice
    build:
      context: ../showservice
      dockerfile: ../showservice/Dockerfile
    image: "fh-erfurt/microkino:showservice"
    depends_on:
      - kafka
      - showservice_db

  bookingservice:
    extends:
      file: microservices.yml
      service: bookingservice
    build:
      context: ../bookingservice
      dockerfile: ../bookingservice/Dockerfile
    image: "fh-erfurt/microkino:bookingservice"
    depends_on:
      - kafka
      - bookingservice_db