###
GET http://localhost:8083/api/address/{{addressId}}

###
GET http://localhost:8083/api/creditCard/{{creditCardId}}

###
GET http://localhost:8083/api/creditCards

###
GET http://localhost:8083/api/ticket/{{ticketId}}

###
GET http://localhost:8083/api/tickets

###
GET http://localhost:8083/api/user/{{userId}}

###
GET http://localhost:8083/api/users

###
GET http://localhost:8082/api/cinema/{{cinemaId}}

###
GET http://localhost:8082/api/cinemaHall/{{cinemaHallId}}

###
GET http://localhost:8082/api/cinemaHalls

###
GET http://localhost:8082/api/cinemas

###
GET http://localhost:8082/api/location/{{locationId}}

###
GET http://localhost:8082/api/locations

###
GET http://localhost:8080/keksbendiger/moviesservice/**

###
POST http://localhost:8081/movies/add

###
GET http://localhost:8081/movies/list

###
POST http://localhost:8081/movies/remove

###
GET http://localhost:8081/movies/{{movieId}}

###
POST http://localhost:8081/screenings/add/{{movieId}}

###
GET http://localhost:8081/screenings/byMovie/{{movieId}}

###
POST http://localhost:8081/screenings/remove