apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: fh-erfurt
spec:
  selector:
    matchLabels:
      app: fh-erfurt
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fh-erfurt
    spec:
      containers:
        - image: ghcr.io/fh-erfurt/microkino:cinemaservice
          name: cinemaservice
          ports:
            - containerPort: 8090