name: "moviesservice2"

on:
  push:
    # run the workflow only on changes
    # to the auth route and auth workflow
    paths:
      - "moviesservice/**"
      - ".github/workflows/moviesservice.yml"
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: keksbendiger/moviesservice
  
defaults:
  run:
    working-directory: moviesservice

jobs:
  test:
     name: GradleTest
     runs-on: ubuntu-latest

     steps:
       - name: checkout
         uses: actions/checkout@v2

       - name: Setup JDK 17
         uses: actions/setup-java@v2
         with:
           java-version: '17'
           distribution: 'temurin'

       - name: Grant Permissions to gradlew
         run: chmod +x gradlew
       - name: Test
         run: ./gradlew test --tests "*"

  build-and-push-image:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Grant Permissions to gradlew
      run: chmod +x gradlew
      
    - name: Execute Gradle build
      run: ./gradlew build -x test 

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./moviesservice/
        file: ./moviesservice/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
