name: "movieservice"

on:
  push:
    # run the workflow only on changes
    # to the auth route and auth workflow
    branches:
      - "main"
    paths:
      - "movieservice/**"
      - ".github/workflows/movieservice.yml"
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
defaults:
  run:
    working-directory: movieservice

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Log in to the Container registry
      uses: docker/login-action@3da7dc6e2b31f99ef2cb9fb4c50fb0971e0d0139
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@766400ca14a75010e7b2e3119aa0d5b46826e8c7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@70cc701b9c4d9e9ef4a5630c16a5121e746a28b2
      with:
        context: ./movieservice/
        file: ./movieservice/Dockerfile
        push: true
        #tags: ${{ steps.meta.outputs.tags }}
        tags: ghcr.io/darthkali/microkino:movieservice
        labels: ${{ steps.meta.outputs.labels }}
        
